rootLogger: INFO, DAILY
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN

  # gateway
  #gateway: DEBUG
  #index.gateway: DEBUG

  # peer shard recovery
  #index.shard.recovery: DEBUG

appender:
  file:
    type: file
    file: /var/log/elasticsearch/elasticsearch.log
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
  DAILY:
    type: org.apache.log4j.DailyRollingFileAppender
    file: /var/log/elasticsearch/elasticsearch.log
    layout:
      type: pattern
      conversionPattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%p] %c:%L - %m%n"
                                                                                     